trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: 'dbMysqlG13S3' # Colocar el nombre de tu ACR
  IMAGE_NAME: 'dbMysqlG13S3' # Colocar el Nombre de Imagen
  SERVICE_CONNECTION_NAME: 'dbMysqlG13S3' # Colocar nombre del Service Connection ubicado en Docker Registry-- Azure Container Registry

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image ACR'
